onie-uninstaller: move common code to onie-uninstaller-common
The patch has been tested in Accton u-boot-arch and x86_64 platforms.

Signed-off-by: Curt Brune <curt@cumulusnetworks.com>

diff --git a/rootconf/u-boot-arch/sysroot-lib-onie/uninstall-arch b/rootconf/u-boot-arch/sysroot-lib-onie/uninstall-arch
--- a/rootconf/u-boot-arch/sysroot-lib-onie/uninstall-arch
+++ b/rootconf/u-boot-arch/sysroot-lib-onie/uninstall-arch
@@ -1,34 +1,15 @@
 # U-Boot specific uninstall routine
 
 #  Copyright (C) 2014,2015 Curt Brune <curt@cumulusnetworks.com>
+#  Copyright (C) 2016 david_yang <david_yang@accton.com>
 #
 #  SPDX-License-Identifier:     GPL-2.0
 
-erase_mass_storage()
-{
-    device=$1
-
-    dev_sz=$(blockdev --getsize64 /dev/$device)
-    cur_sz=0
-    count=0
-    n_mb=8
-    step=$(( $n_mb * 1024 * 1024 ))
-    total=$(( $dev_sz + $step - 1 ))
-    total=$(( $total / $step ))
-    mb_sz=$(( $dev_sz / ( 1024 * 1024 ) ))
-    printf "${log_pre}Erasing internal mass storage device: /dev/$device (${mb_sz}MB)\n"
-    if [ "$onie_testing" != "y" ] ; then
-        dd if=/dev/urandom of=/tmp/junk.bin bs=1M count=$n_mb > /dev/null 2>&1
-        while [ $cur_sz -lt $dev_sz ] ; do
-            dd if=/tmp/junk.bin of=/dev/$device bs=$step seek=$count > /dev/null 2>&1
-            count=$(( $count + 1 ))
-            cur_sz=$(( $step * $count ))
-            printf "\r  Percent complete: %02u%%" $(( ($count * 100) / $total ))
-        done
-        printf "\n"
-    fi
-    printf "${log_pre}Erase complete.\n"
+[ -r "$lib_dir/onie-uninstaller-common" ] || {
+    echo "ERROR: Unable to find onie-uninstaller-common"
+    exit 1
 }
+. $lib_dir/onie-uninstaller-common
 
 uninstall_system()
 {
