onie-sysinfo -e, onie-sysinfo -s: fixing EEPROM read error flow
Error flow note:
"ERROR: TLV code not present" is pointed to onie-syseeprom's stdout,
which is not printed.
An additional more generic "incorrect TLV field number" is printed at
/var/log/onie.log

Tests:
Good flow:
ONIE:~ # onie-sysinfo -e
ONIE:~ # onie-sysinfo -s
ONIE:~ # onie-sysinfo -a
ONIE:~ # tail /var/log/onie.log
Error flow:
- Edit /lib/onie/sysinfo-arch to point to incorrect TLV field number
ONIE:~ # onie-sysinfo -e
ONIE:~ # onie-sysinfo -s
ONIE:~ # onie-sysinfo -a
ONIE:~ # tail /var/log/onie.log

Signed-off-by: Doron Tsur <doront@mellanox.com>

diff --git a/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch b/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
--- a/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
+++ b/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
@@ -12,10 +12,10 @@ get_serial_num_arch()
 {
     if [ -x /usr/bin/onie-syseeprom ] ; then
         sn="$(onie-syseeprom -g 0x23)"
-        if [ -n "$sn" ] ; then
+        if [ $? -eq 0 -a -n "$sn" ] ; then
             echo $sn
         else
-            log_console "Unable to find 'Serial Number' TLV in EEPROM data."
+            log_console_msg "Unable to find 'Serial Number' TLV in EEPROM data."
         fi
     fi
 }
@@ -26,10 +26,10 @@ get_ethaddr_arch()
 {
     if [ -x /usr/bin/onie-syseeprom ] ; then
         mac="$(onie-syseeprom -g 0x24)"
-        if [ -n "$mac" ] ; then
+        if [ $? -eq 0 -a -n "$mac" ] ; then
             echo $mac
         else
-            log_console "Unable to find 'Base MAC Address' TLV in EEPROM data."
+            log_console_msg "Unable to find 'Base MAC Address' TLV in EEPROM data."
         fi
     fi
 }
