Adding -P part number flag to onie-sysinfo
Tests:
ONIE:~ # onie-sysinfo
x86_64-mlnx_x86-r5.0
ONIE:~ # onie-sysinfo -a
MT*<SN>* MSX1710-BS2F2E F4:52:14:DF:87:1E ocp_master-201411160936.1100-dirty
33049 mlnx_x86 5.0 x86_64-mlnx_x86-r5.0 x86_64 1 gpt 2014-11-16T09:37+0200
ONIE:~ # onie-sysinfo -P
MSX1710-BS2F2E
ONIE:~ # onie-sysinfo -p
x86_64-mlnx_x86-r5.0
ONIE:~ # onie-sysinfo -h
onie-sysinfo [-hsevimrpcfdatP]
...
        -s
                Serial Number

        -P
                Part Number
...
ONIE:~ # onie-sysinfo -s
MT*<SN>*
ONIE:~ # onie-sysinfo -i
33049
ONIE:~ # onie-sysinfo -r
5.0
< Edit /lib/onie/sysinfo-arch to point to incorrect TLV field of part number >
ONIE:~ # onie-sysinfo -P
Unknown
ONIE:~ # onie-sysinfo -a
MT*<SN>* Unknown F4:52:14:DF:87:1E ...
ONIE:~ # tail /var/log/onie.log
Nov 16 09:37:36 <hostname> local0.info onie: ONIE: Unable to find
'Part Number' TLV in EEPROM data.
Nov 16 09:37:51 <hostname> local0.info onie: ONIE: Unable to find
'Part Number' TLV in EEPROM data.

Signed-off-by: Doron Tsur <doront@mellanox.com>

diff --git a/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch b/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
--- a/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
+++ b/rootconf/x86_64/sysroot-lib-onie/sysinfo-arch
@@ -34,6 +34,18 @@ get_ethaddr_arch()
     fi
 }
 
+get_part_num_arch()
+{
+    if [ -x /usr/bin/onie-syseeprom ] ; then
+        pn="$(onie-syseeprom -g 0x22)"
+        if [ $? -eq 0 -a -n "$pn" ] ; then
+            echo $pn
+        else
+            log_console_msg "Unable to find 'Part Number' TLV in EEPROM data."
+        fi
+    fi
+}
+
 # Local Variables:
 # mode: shell-script
 # eval: (sh-set-shell "/bin/sh" t nil)
