Add support for x86 DIAG partitions
Reviewed By: dustin

This patch adds support to x86 ONIE for handling an external DIAG OS
that resides in its own partition.  The DIAG OS is installed just like
a NOS, with a few additional requirements.

For ONIE the main place where the DIAG OS partition matters is during
the "OS uninstall" operation.  ONIE needs to be careful and not remove
the DIAG OS during this operation.

The requirements of a DIAG OS installer follow.  The "OS uninstall"
operation depends on these requirements being met.

- Install the diag OS into it's own partition.

- When the machine's partition table is GPT:

  + name the diag partition "<SOMETHING>-DIAG".  See the man page for
    sgdisk(8) and the --change-name option.

  + set the GPT 'system partition' attribute bit (bit 0).  See the man
    page for sgdisk(8) and the --attributes option.

  + when creating the file system on the diag partition set the file
    system label to "<SOMETHING>-DIAG", the same string as used for
    the GPT partition label.  See mkfs.ext4(8) and the -L option.

  The "-DIAG" suffix and the 'system partition' bit is how ONIE
  recoginizes that the partition is a DIAG partition.  This
  information also helps a NOS installer recognize the partitions as
  "special" and leave them alone.

- When the machine's partition table is MSDOS (please no one use MSDOS
  partitions):

  + All we can do in this case is use the file system label.  When
    creating the file system on the diag partition set the file system
    label to "<SOMETHING>-DIAG".  See mkfs.ext4(8) and the -L option.

- When installing the diag image, install GRUB into the MBR, just like
  the demo OS does.

- Also install GRUB into the diag partition.  This will allow a NOS to
  "chainload" the diag OS.

- The grub.cfg for the diag partition should contain all menu entries
  the diag OS needs, plus one entry to chainload ONIE.

When provisioning a machine in the factory the order of operations
would be:

1. Install ONIE on the machine

2. From ONIE use any of the regular NOS install methods to install the
   DIAG OS.

Testing Done:

Using the x86_64 virtual machine exercised:

- installing ONIE

- installing a demo DIAG OS

- installing a demo NOS

- invoking the OS uninstall procedure and verifying the demo NOS was
  removed, while leaving the DIAG OS intact.

diff --git a/rootconf/x86_64/sysroot-lib-onie/uninstall-arch b/rootconf/x86_64/sysroot-lib-onie/uninstall-arch
--- a/rootconf/x86_64/sysroot-lib-onie/uninstall-arch
+++ b/rootconf/x86_64/sysroot-lib-onie/uninstall-arch
@@ -93,6 +93,16 @@ should_delete_gpt_partition()
             # echo "skipping ONIE part"
             return 1
             ;;
+        *-DIAG)
+            # check system attributes
+            attr=$(sgdisk -i $2 /dev/$1 | grep 'Attribute flags')
+            attr=${attr##*: }
+            if [ "$attr" = "0000000000000001" ] ; then
+                # system attribute is set, skip this part
+                # echo "skipping DIAG part"
+                return 1
+            fi
+            ;;
         *)
             return 0
             ;;
@@ -110,7 +120,7 @@ should_delete_gpt_partition()
 should_delete_msdos_partition()
 {
     # check for ONIE-BOOT file system volume label
-    blkid /dev/${1}$2 | grep -q ONIE-BOOT && return 1
+    blkid /dev/${1}$2 | egrep -q '(ONIE-BOOT|-DIAG$)' && return 1
     return 0
 }
 
@@ -118,15 +128,16 @@ uninstall_system()
 {
 
     # Clean up block device that contains ONIE
-    blk_dev=$(blkid | grep ONIE-BOOT | awk '{print $1}' | sed -e 's/[0-9]://' | head -n 1 | sed -e 's#/dev/##')
+    onie_dev=$(blkid | grep ONIE-BOOT | awk '{print $1}' | sed -e 's/:.*$//')
+    blk_dev=$(echo $onie_dev | sed -e 's/[0-9]//' | sed -e 's#/dev/##')
 
     [ -b "/dev/$blk_dev" ] || {
         echo "Error: Unable to determine block device of ONIE install"
         exit 1
     }
 
-    # Wipe out and delete all partitions, except for the ONIE and GRUB
-    # partitions.
+    # Wipe out and delete all partitions, except for important ones,
+    # like GRUB, ONIE and possibly a DIAG.
     ls -d /sys/block/$blk_dev/${blk_dev}* | sed -e "s/^.*$blk_dev//" | while read part ; do
         if eval $should_delete_partition $blk_dev $part ; then
             erase_part $blk_dev $part
@@ -137,12 +148,35 @@ uninstall_system()
     # probably installed there.
 
     boot_dev="/dev/$blk_dev"
+
+    # Install ONIE GRUB in MBR and ONIE partition
     core_img="$onie_boot_mnt/grub/i386-pc/core.img"
     [ -f "$core_img" ] && chattr -i $core_img
     grub-install --boot-directory="$onie_boot_mnt" --recheck "$boot_dev" || {
         echo "ERROR: grub-install failed on: $boot_dev"
         exit 1
     }
+    grub_install_log=$(mktemp)
+    grub-install --force --boot-directory="$onie_boot_mnt" \
+        --recheck "$onie_dev" > /$grub_install_log 2>&1 || {
+        echo "ERROR: grub-install failed on: $onie_dev"
+        cat $grub_install_log && rm -f $grub_install_log
+        exit 1
+    }
+    rm -f $grub_install_log
+    [ -f "$core_img" ] && chattr +i $core_img
+
+    # If there is a diag partition add a chainload entry for it.
+    diag_label=$(blkid | grep -- '-DIAG"' | sed -e 's/^.*LABEL="//' -e 's/".*$//')
+    if [ -n "$diag_label" ] ; then
+        cat <<EOF >> $grub_root_dir/grub.cfg
+menuentry '$diag_label $onie_platform' {
+        search --no-floppy --label --set=root $diag_label
+        echo    'Loading $diag_label $onie_platform ...'
+        chainloader +1
+}
+EOF
+    fi
 
     # Return to install mode on the next boot
     onie-boot-mode -q -o install
