create-release: add a little protection
Add a 'are you sure?' message to the create-release script to help
avoid making mistakes.

Signed-off-by: Curt Brune <curt@cumulusnetworks.com>

diff --git a/build-config/scripts/create-release b/build-config/scripts/create-release
--- a/build-config/scripts/create-release
+++ b/build-config/scripts/create-release
@@ -42,8 +42,23 @@ git checkout -b "$branch"
 echo $version > conf/onie-release
 git add conf/onie-release
 git commit conf/onie-release -m 'Add release version'
-git push origin $branch
 
 echo "Tagging $version ..."
 git tag -a $version -F "$release_notes"
-git push origin $version
+
+echo "Please review the branch name, tag name and release notes..."
+echo "branch: $branch"
+echo "tag   : $tag"
+echo "Release Notes:"
+cat "$release_notes"
+
+read -p "Pushing new branch and tag.  Are you sure? (N/y)" answer
+case "$answer" in
+    Y|y)
+        true
+        ;;
+    *)
+        echo "Aborting...." && exit 1
+esac
+
+git push origin $branch $version
