Use local download cache with ONIE_USE_SYSTEM_DOWNLOAD_CACHE=TRUE
Setting ONIE_USE_SYSTEM_DOWNLOAD_CACHE=TRUE when invokging a build
will export that variable to be interpreted by scripts/fetch-package .

If set = TRUE, the fetch-package script will look under
/var/cache/onie/download for packages it would otherwise pull from
http://mirror.opencompute.org/onie.

The presumption is that the user would have set up this directory
ahead of time, either by copying files downloaded for the targets
they are building, or, in the case of a maintainer who has to
rebuild everything with some frequency, just downloading everything
from the OpenCompute mirror with:

 wget --recursive --cut-dirs=2 --no-host-directories \
  --no-parent --reject "index.html" http://mirror.opencompute.org/onie/

Note that the script will fail if a package is not present. This
is a 'feature' that will let the user know their cache is incomplete.

Signed-off-by: Alex Doyle <adoyle@cumulusnetworks.com>

diff --git a/build-config/scripts/fetch-package b/build-config/scripts/fetch-package
--- a/build-config/scripts/fetch-package
+++ b/build-config/scripts/fetch-package
@@ -2,7 +2,7 @@
 
 #  Copyright (C) 2013-2014 Curt Brune <curt@cumulusnetworks.com>
 #  Copyright (C) 2016 Pankaj Bansal <pankajbansal3073@gmail.com>
-#  Copyright (C) 2019 Alex Doyle <adoyle@cumulusnetworks.com>
+#  Copyright (C) 2019-2020 Alex Doyle <adoyle@cumulusnetworks.com>
 #
 #  SPDX-License-Identifier:     GPL-2.0
 
@@ -28,6 +28,10 @@ EOF
 # Once the local ./build/download directory is populated,
 # those packages can be copied here to be referenced should
 # the network become unavailable.
+# Populate with:
+#     wget --recursive --cut-dirs=2 --no-host-directories \
+#     --no-parent --reject "index.html" http://mirror.opencompute.org/onie/
+
 DOWNLOAD_CACHE_DIR="/var/cache/onie/download"
 
 OUTDIR=$1
@@ -65,44 +69,50 @@ if [ -r "${OUTDIR}/${FILE}" ] ; then
 else
     download=no
 
-    while [ $# -ge 1 ] ; do
-        URL="$1/$FILE"
-	echo "  Downloading $FILE from: $URL"
-        wget --no-verbose --no-check-certificate -O "${OUTDIR}/${FILE}" $URL
-        if [ $? -eq 0 ] ; then
-            # stop
-            download=yes
-            break
-        else
-	    rm -f "${OUTDIR}/${FILE}"
-        fi
-        shift
-    done
-    if [ "$download" = "no" ] ; then
-	# Has a package cache has been set up on the local system, mirroring
-	# http://mirror.opencompute.org/onie/
-	# Look there too.
-	if [ -e "${DOWNLOAD_CACHE_DIR}"/"${FILE}" ];then
-	    echo "  Copying      $FILE from system cache at ${DOWNLOAD_CACHE_DIR}"
-	    cp ${DOWNLOAD_CACHE_DIR}/${FILE} "${OUTDIR}/${FILE}"
-	    download=yes
+	# Allow setting of an environment variable to skip download and
+	# go straight to the system package cache.
+	if [ "$ONIE_USE_SYSTEM_DOWNLOAD_CACHE" = "TRUE" ];then
+		echo "  Getting ${FILE} from ${DOWNLOAD_CACHE_DIR} "
+	else
+		while [ $# -ge 1 ] ; do
+			URL="$1/$FILE"
+			echo "  Downloading $FILE from: $URL"
+			wget --no-verbose --no-check-certificate -O "${OUTDIR}/${FILE}" $URL
+			if [ $? -eq 0 ] ; then
+				# stop
+				download=yes
+				break
+			else
+				rm -f "${OUTDIR}/${FILE}"
+			fi
+			shift
+		done
 	fi
+    if [ "$download" = "no" ] ; then
+        # Has a package cache has been set up on the local system, mirroring
+        # http://mirror.opencompute.org/onie/
+        # Look there too.
+        if [ -e "${DOWNLOAD_CACHE_DIR}"/"${FILE}" ];then
+            echo "  Copying      $FILE from system cache at ${DOWNLOAD_CACHE_DIR}"
+            cp ${DOWNLOAD_CACHE_DIR}/${FILE} "${OUTDIR}/${FILE}"
+            download=yes
+        fi
     fi
     if [ "$download" != "yes" ] ; then
-	    echo ""
-            echo "  ERROR:  Unable to download $FILE from $URL"
-	    echo ""
-            exit 1
+        echo ""
+        echo "  ERROR:  Unable to download $FILE from $URL"
+        echo ""
+        exit 1
     else
-	echo "  Got          $FILE"
+        echo "  Got          $FILE"
     fi
     echo ""
 fi
 
 # Verify SHA1
 cd $OUTDIR && sha1sum -c ${SHA1DIR}/${FILE}.sha1 || {
-    echo " ERROR: Unable to verify sha1 for ${FILE}"
-    exit 1
-}
+        echo " ERROR: Unable to verify sha1 for ${FILE}"
+        exit 1
+    }
 
 exit 0
