fetch-package: always verify cached packages
The fetch-package script has a bug where a corrupt package marked as
BAD on one run will be seen as OK on subsequent runs.  The problem is
on subsequent runs the script only checks for the presence of the
package, but not the checksum.

This patch makes fetch-package validate the checksum in all cases.  If
the package already exists only the download is skipped, but the
cached package is still validated.

diff --git a/build-config/scripts/fetch-package b/build-config/scripts/fetch-package
--- a/build-config/scripts/fetch-package
+++ b/build-config/scripts/fetch-package
@@ -48,29 +48,26 @@ shift 3
     exit 1
 }
 
-# File already downloaded
-[ -r "${OUTDIR}/${FILE}" ] && {
+if [ -r "${OUTDIR}/${FILE}" ] ; then
     echo "Using cached ${OUTDIR}/${FILE}"
-    exit 0
-}
-
-download=no
-while [ $# -ge 1 ] ; do
-    URL="$1/$FILE"
-    wget --no-verbose -O "${OUTDIR}/${FILE}" $URL
-    if [ $? -eq 0 ] ; then
-        # stop
-        download=yes
-        break
-    else
-        rm -f "${OUTDIR}/${FILE}"
+else
+    download=no
+    while [ $# -ge 1 ] ; do
+        URL="$1/$FILE"
+        wget --no-verbose -O "${OUTDIR}/${FILE}" $URL
+        if [ $? -eq 0 ] ; then
+            # stop
+            download=yes
+            break
+        else
+            rm -f "${OUTDIR}/${FILE}"
+        fi
+        shift
+    done
+    if [ "$download" != "yes" ] ; then
+        echo "ERROR:  Unable to download $FILE"
+        exit 1
     fi
-    shift
-done
-
-if [ "$download" != "yes" ] ; then
-    echo "ERROR:  Unable to download $FILE"
-    exit 1
 fi
 
 # Verify SHA1
