Set partition attributes for ONIE GPT partitions
The GUUID Partition Table format allocates 64 bits of attributes for
each partition.  Of interest here are the "system partition" (bit 0)
and the "read only" (bit 60) attributes.

During ONIE installation set the partition attributes as follows:

GRUB_BOOT   -- system partition, read-only
ONIE_BOOT   -- system partition, read-only
ONIE_CONFIG -- system partition

The goal is that NOS installers will respect these partition
attributes and avoid destroying/modifying the ONIE partitions.

Reviewed By: dustin

Testing Done:

Installed ONIE on the kvm_x86_64 machine and verified the partition
attributes were set correctly using sgdisk:

    ONIE:/ # sgdisk -i 1 /dev/vda
    Partition GUID code: 21686148-6449-6E6F-744E-656564454649 (BIOS boot partition)
    Partition unique GUID: 7442636D-5160-4872-A8AA-90078D97E556
    First sector: 2048 (at 1024.0 KiB)
    Last sector: 6143 (at 3.0 MiB)
    Partition size: 4096 sectors (2.0 MiB)
==> Attribute flags: 1000000000000001
    Partition name: 'GRUB-BOOT'

    ONIE:/ # sgdisk -i 2 /dev/vda
    Partition GUID code: 7412F7D5-A156-4B13-81DC-867174929325 (ONIE boot)
    Partition unique GUID: 81C55EA1-48E0-44F7-A557-2990C3CB9490
    First sector: 6144 (at 3.0 MiB)
    Last sector: 268287 (at 131.0 MiB)
    Partition size: 262144 sectors (128.0 MiB)
==> Attribute flags: 1000000000000001
    Partition name: 'ONIE-BOOT'

    ONIE:/ # sgdisk -i 3 /dev/vda
    Partition GUID code: D4E6E2CD-4469-46F3-B5CB-1BFF57AFC149 (ONIE config)
    Partition unique GUID: E6729645-42C8-45F2-9581-6C6CBD47BB0D
    First sector: 268288 (at 131.0 MiB)
    Last sector: 276479 (at 135.0 MiB)
    Partition size: 8192 sectors (4.0 MiB)
==> Attribute flags: 0000000000000001
    Partition name: 'ONIE-CONFIG'

diff --git a/installer/x86_64/install-arch b/installer/x86_64/install-arch
--- a/installer/x86_64/install-arch
+++ b/installer/x86_64/install-arch
@@ -119,8 +119,28 @@ create_part()
 
     [ "$verbose" = "yes" ] && echo "Creating $label on: ${onie_dev}$part"
 
+    # Create a new partition with the given start, size, gpt_uuid and
+    # name.  Additionally set partition attributes based on the
+    # particular partition.
+
+    case "$p" in
+        grub_boot | onie_boot)
+            # Set system partition (bit 0) and read-only (bit 60)
+            # attributes.
+            attr_bitmask="0x1000000000000001"
+            ;;
+        onie_config)
+            # Set system partition (bit 0) attributes.
+            attr_bitmask="0x1"
+            ;;
+        *)
+        echo "ERROR: unknown ONIE partition name: $p"
+        exit 1
+    esac
+
     sgdisk --new=$part:$start:+$size \
         --typecode=$part:$gpt_uuid \
+        --attributes=$part:=:$attr_bitmask \
         --change-name=$part:"$label" "$onie_dev" || {
         echo "ERROR: Problems creating $label partition $part on: $onie_dev"
         exit 1
