ONIE installer: allow platforms to define the ONIE install block device
The problem we are trying to solve is:

   How to determine the block device upon which to install ONIE?

The question is complicated when multiple block devices are present,
i.e. perhaps the system has two hard drives installed or maybe a USB
memory stick is momentarily installed.  For example the internal disk
device usually shows up as /dev/sda under Linux, but maybe with a USB
drive connected the internal disk now shows as /dev/sdb.

This patch forces each platform to specify how to determine the target
ONIE install device.

diff --git a/installer/x86_64/install-arch b/installer/x86_64/install-arch
--- a/installer/x86_64/install-arch
+++ b/installer/x86_64/install-arch
@@ -6,6 +6,11 @@
 }
 . ./installer.conf
 
+onie_dev="$(install_device_platform)"
+[ $? -eq 0 ] || {
+    echo "WARNING: Unable to find ONIE install block device."
+}
+
 args_arch="d:"
 
 usage_arch=$(cat <<EOF
@@ -181,7 +186,7 @@ install_onie()
     . ./onie-blkdev-common
 
     # Find install device.
-    # - Default value from  burned in platform.conf
+    # - Default value from burned in install.conf
     # - Overridden with -d CLI arg
     [ -b "$onie_dev" ] || {
         echo "ERROR: Invalid ONIE install device: $onie_dev"
