onie-boot-init: (re)-init the ONIE-CONFIG partition
Added a new command that (re)-initializes the ONIE-CONFIG partition.

Using this command wipes any configuration from ONIE-CONFIG and
restores it to a pristine state.

This command is also used by the ONIE self-update installer to
initialize the ONIE-CONFIG partition.

The command does the following:

- destroys the file system and re-formats the partition

- seeds the fresh file system with files from the read-only ONIE-BOOT
  partition.

diff --git a/installer/x86_64/install-arch b/installer/x86_64/install-arch
--- a/installer/x86_64/install-arch
+++ b/installer/x86_64/install-arch
@@ -276,23 +276,14 @@ install_onie()
     fi
 
     if [ "$format_disk" = "yes" ] || [ "$bad_config" = "yes" ] ; then
-        # ONIE-CONFIG is unmountable.  Format it and install skeletal
-        # config files.
+        # Initialize the ONIE-CONFIG partition.
 
-        # Create file system on ONIE-CONFIG partition
-        [ "$verbose" = "yes" ] && echo "Creating $onie_config_fs_type file system on: $onie_config_dev"
-        mkfs.$onie_config_fs_type -q -L $onie_config_label $onie_config_dev || {
-            echo "Error: Unable to create $onie_config_fs_type file system on: $onie_config_dev"
+        # Use the new onie-tools from *this* installer.
+        [ "$verbose" = "yes" ] && echo "Initializing ONIE-CONFIG partition"
+        /mnt/onie-tools/bin/onie-boot-init -fq -d $onie_config_dev || {
+            echo "Error: Problems initializing ONIE boot configuration"
             exit 1
         }
-
-        mount -o defaults,rw -t $onie_config_fs_type $onie_config_dev $onie_config_mnt || {
-            echo "Error: Unable to mount $onie_config_label ($onie_config_dev) on ${onie_config_mnt}"
-            exit 1
-        }
-
-        # Install skeletal grub.d on $onie_config_dev
-        cp -a grub/grub.d.skel $onie_config_mnt/grub.d
 
     else
         # Migrate existing config - check running onie_config_version
@@ -319,7 +310,10 @@ install_onie()
             exit 1
         }
 
-        umount $onie_config_mnt
+        umount $onie_config_mnt || {
+            echo "Error: Problems un-mouningt ONIE-CONFIG ($onie_config_dev) from ${onie_config_mnt}"
+            exit 1
+        }
 
         # Create file system on ONIE-CONFIG partition
         [ "$verbose" = "yes" ] && echo "Creating $onie_config_fs_type file system on: $onie_config_dev"
@@ -339,12 +333,12 @@ install_onie()
             exit 1
         }
 
-    fi
+        umount $onie_config_mnt || {
+            echo "Error: Problems un-mouningt ONIE-CONFIG ($onie_config_dev) from ${onie_config_mnt}"
+            exit 1
+        }
 
-    umount $onie_config_mnt || {
-        echo "Error: Problems un-mouningt ONIE-CONFIG ($onie_config_dev) from ${onie_config_mnt}"
-        exit 1
-    }
+    fi
 
     # Use the new onie-tools from *this* installer to update the ONIE
     # boot configuration.  This is required to pick up any new
@@ -353,6 +347,12 @@ install_onie()
     [ "$verbose" = "yes" ] && echo "Updating ONIE boot configuration"
     /mnt/onie-tools/bin/onie-boot-update -q || {
         echo "Error: Problems updating ONIE boot configuration"
+        exit 1
+    }
+
+    # Done with the onie-tools
+    umount /mnt/onie-tools || {
+        echo "Error: Problems un-mouningt onie-tools"
         exit 1
     }
 
diff --git a/rootconf/x86_64/sysroot-lib-onie/onie-blkdev-common b/rootconf/x86_64/sysroot-lib-onie/onie-blkdev-common
--- a/rootconf/x86_64/sysroot-lib-onie/onie-blkdev-common
+++ b/rootconf/x86_64/sysroot-lib-onie/onie-blkdev-common
@@ -67,14 +67,14 @@ onie_mount_partitions()
     trap onie_umount_partitions EXIT
 
     mkdir -p $onie_boot_mnt
-    mount -o defaults,ro -t $onie_boot_fs_type LABEL=ONIE-BOOT $onie_boot_mnt || {
-        echo "ERROR: Problems mounting ONIE-BOOT on $onie_boot_mnt"
+    mount -o defaults,ro -t $onie_boot_fs_type "LABEL=$onie_boot_label" $onie_boot_mnt || {
+        echo "ERROR: Problems mounting $onie_boot_label on $onie_boot_mnt"
         exit 1
     }
 
     mkdir -p $onie_config_mnt
-    mount -o defaults,rw -t $onie_config_fs_type LABEL=ONIE-CONFIG $onie_config_mnt || {
-        echo "ERROR: Problems mounting ONIE-CONFIG on $onie_config_mnt"
+    mount -o defaults,rw -t $onie_config_fs_type "LABEL=$onie_config_label" $onie_config_mnt || {
+        echo "ERROR: Problems mounting $onie_config_label on $onie_config_mnt"
         exit 1
     }
 
