Change default installer file name
Reviewed By: matt, dustin

The default installer file name is changed from a single file to a
list of files, with descreasing precision.  Formerly the default
installer name was:

  onie-installer-<platform>-<arch>

In most place the single file is now replaced with the following list
of names:

  onie-installer-<arch>-<platform>
  onie-installer-<platform>
  onie-installer-<arch>
  onie-installer

This allows for simple installs with minimal infrastructure
configuration and without exact knowledge of the platform name or
architecture.

The list of file names is used for locally attached storage (USB) and
for the inexact HTTP URL methods.

The TFTP PXE-like waterfall uses onie-installer-<arch>-<platform>
during the cascade, but at the end uses the 4 default names at the
root of the server.

See the updated documentation for details and examples.

diff --git a/rootconf/default/bin/exec_installer b/rootconf/default/bin/exec_installer
--- a/rootconf/default/bin/exec_installer
+++ b/rootconf/default/bin/exec_installer
@@ -151,14 +151,42 @@ url_run()
 # Try various HTTP URLs
 http_download()
 {
-    # Try neighbors
+    # Build list of HTTP servers to try
+    http_servers=
+
+    # HTTP server IP only
+    if [ -n "$onie_disco_wwwsrv" ] ; then
+        http_servers="$http_servers $onie_disco_wwwsrv"
+    fi
+
+    # Try BOOTP next-server IP as HTTP
+    if [ -n "$onie_disco_siaddr" ] ; then
+        http_servers="$http_servers $onie_disco_siaddr"
+    fi
+
+    # Try DHCP server IP as HTTP
+    if [ -n "$onie_disco_serverid" ] ; then
+        http_servers="$http_servers $onie_disco_serverid"
+    fi
+
+    # Add link local neighbors
     while [ ${#onie_neighs} -gt 0 ] ; do
         n=${onie_neighs%%,*}
         onie_neighs=${onie_neighs#*,}
         tmp=$(echo $n | sed -e 's/-/%/g');
+        http_servers="$http_servers $tmp"
+    done
+
+    # make list items unique, while preserving list order
+    ulist=$({ cnt=0; for s in $http_servers ; do printf "%d\t%s\n" $cnt $s ; cnt=$(( $cnt + 1 )) ; done ; } | \
+        sort -u -k2 | sort -n | cut -f2-)
+    for server in $ulist ; do
         # Check if server appears to be alive
-        nc -w 3 $tmp 80 -e /bin/true > /dev/null 2>&1 && {
-            url_run "http://$tmp/$onie_default_filename" && return 0
+        nc -w 10 $server 80 -e /bin/true > /dev/null 2>&1 && {
+            # Try list of default file names
+            for f in $onie_default_filenames ; do
+                url_run "http://$server/$f" && return 0
+            done
         }
     done
 
@@ -206,19 +234,9 @@ waterfall()
         done
     fi
 
-    # Next is root of tftp server
-    wf_paths="$wf_paths $onie_default_filename"
-    
-    # HTTP server IP waterfall
-    if [ -n "$onie_disco_wwwsrv" ] ; then
-        # First check if server appears to be alive
-        nc -w 3 $onie_disco_wwwsrv 80 -e /bin/true > /dev/null 2>&1 && {
-            for p in $wf_paths ; do
-                url_run "http://$onie_disco_wwwsrv/$p" && return 0
-            done
-        }
-    fi
-    
+    # Next is root of tftp server -- try all default filenames
+    wf_paths="$wf_paths $onie_default_filenames"
+
     # TFTP waterfall
     if [ -n "$onie_disco_siaddr" ] ; then
         for p in $wf_paths ; do
@@ -240,27 +258,30 @@ local_fs_run()
         p=${onie_local_parts%%,*}
         onie_local_parts=${onie_local_parts#*,}
         mount $p $mp > /dev/null 2>&1 && {
-            if [ -r $mp/$onie_default_filename ] ; then
-                # copy to /tmp, which is a tmpfs -- installer needs to
-                # run with everything unmounted.
-                tmp_copy=$(mktemp -p /tmp)
-                cp $mp/$onie_default_filename $tmp_copy || {
-                    log_failure_msg "local_fs_run():$p Unable to copy $onie_default_filename to tmpfs"
-                    rm -f $tmp_copy
-                    return 1
-                }
-                sync ; sync
-                umount $p
-                ln -sf $tmp_copy $onie_installer || {
-                    log_failure_msg "local_fs_run():$p Unable to make symlink to $onie_installer in tmpfs"
-                    rm -f $tmp_copy
-                    return 1
-                }
-                run_installer "file:/$p/$onie_default_filename" && return 0
-                rm -f $tmp_copy $onie_installer
-            else
-                umount $p
-            fi
+            for f in $onie_default_filenames ; do
+                if [ -r $mp/$f ] ; then
+                    # copy to /tmp, which is a tmpfs -- installer needs to
+                    # run with everything unmounted.
+                    tmp_copy=$(mktemp -p /tmp)
+                    cp $mp/$f $tmp_copy || {
+                        log_failure_msg "local_fs_run():$p Unable to copy $mp/$f to tmpfs"
+                        rm -f $tmp_copy
+                        return 1
+                    }
+                    sync ; sync
+                    umount $p
+                    ln -sf $tmp_copy $onie_installer || {
+                        log_failure_msg "local_fs_run():$p Unable to make symlink to $onie_installer in tmpfs"
+                        rm -f $tmp_copy
+                        return 1
+                    }
+                    run_installer "file:/$p/$f" && return 0
+                    rm -f $tmp_copy $onie_installer
+                    # re-mount it to look for more files
+                    mount $p $mp > /dev/null 2>&1
+                fi
+            done
+            umount $p
         }
     done
     rm -rf $mp
