demo OS: update to installing the ONIE tools
Tracking changes to the core onie-tools interface.

Reviewed-By: dustin

diff --git a/demo/os/x86_64/bin/mount-onie b/demo/os/x86_64/bin/mount-onie
--- a/demo/os/x86_64/bin/mount-onie
+++ b/demo/os/x86_64/bin/mount-onie
@@ -21,8 +21,8 @@ mount -o defaults,ro LABEL=ONIE-BOOT $onie_boot_mnt || {
 }
 
 # Run ONIE provided mount script
-$onie_boot_mnt/mount_onie.sh || {
-    echo "ERROR: Problems mounting ONIE tools partitions"
+$onie_boot_mnt/mount-onie-tools || {
+    echo "ERROR: Problems mounting ONIE tools"
     exit 1
 }
 
