Update modified files to be compatible with mainline, remove "BOOT" label support.

diff --git a/machine/im_n29xx_t40n/rootconf/sysroot-lib-onie/onie-blkdev-common b/machine/im_n29xx_t40n/rootconf/sysroot-lib-onie/onie-blkdev-common
--- a/machine/im_n29xx_t40n/rootconf/sysroot-lib-onie/onie-blkdev-common
+++ b/machine/im_n29xx_t40n/rootconf/sysroot-lib-onie/onie-blkdev-common
@@ -10,7 +10,7 @@ onie_root_dir="${common_boot_mnt}/onie"
 onie_config_dir_orig="${common_boot_mnt}/onie-config"
 onie_config_ramdisk_dir="/onie-config-ramdisk"
 
-# Determine current location of onie root 
+# Determine current location of onie root
 # and configuration directories, create them if necessary
 if [ -d "${common_boot_mnt}" ] ; then
     if [ ! -d "${onie_root_dir}" ] ; then
@@ -43,9 +43,6 @@ onie_update_log="$onie_update_dir/update.log"
 common_boot_fs_type="ext2"
 onie_boot_fs_type="${common_boot_fs_type}"
 
-# This platform uses two alternative labels for
-# /boot filesystem
-common_boot_label="BOOT"
 onie_boot_label="ONIE-BOOT"
 
 # Presence of this file indicates successful fsck
@@ -63,13 +60,16 @@ onie_get_boot_dev()
 	grep ' LABEL="'"${onie_boot_label}"'" ' | sed -e 's/:.*$//')
     if [ -n "${device}" ] ; then
         echo -n "${device}"
-    else
-        device=$(echo "${blkid_output}" | \
-	  grep ' LABEL="'"${common_boot_label}"'" ' | sed -e 's/:.*$//')
-        if [ -n "${device}" ] ; then
-            echo -n "${device}"
-        fi
     fi
+}
+
+# Return the /dev disk corresponding to $onie_boot_label if it exists.
+onie_get_boot_disk()
+{
+    local disk=$(onie_get_boot_dev)
+    # Strip off the numbers
+    disk="${disk%%[0-9]*}"
+    [ -n "$disk" ] && echo -n "$disk"
 }
 
 # Return the label for /boot device
@@ -80,12 +80,6 @@ onie_get_boot_label()
 	grep ' LABEL="'"${onie_boot_label}"'" ' | sed -e 's/:.*$//')
     if [ -n "${device}" ] ; then
         echo -n "${onie_boot_label}"
-    else
-        device=$(echo "${blkid_output}" | \
-	  grep ' LABEL="'"${common_boot_label}"'" ' | sed -e 's/:.*$//')
-        if [ -n "${device}" ] ; then
-            echo -n "${common_boot_label}"
-        fi
     fi
 }
 
@@ -190,7 +184,7 @@ onie_umount_partitions()
             rc=$(( $rc + 1 ))
         }
     }
-    
+
     return $rc
 }
 
@@ -207,10 +201,10 @@ onie_mount_partitions()
 {
     [ "$1" = "keep_mounted" -o "$2" = "keep_mounted" ] || \
     trap onie_umount_partitions EXIT
-    
+
     writeopt="ro"
     [ "$1" = "write" -o "$2" = "write" ] && writeopt="rw"
-    
+
     label=$(onie_get_boot_label)
 
     [ -n "${label}" ] || rm -f "${fsck_flag_file}"
@@ -224,7 +218,7 @@ onie_mount_partitions()
 		touch "${fsck_flag_file}"
         }
     }
-    
+
     [ -f "${fsck_flag_file}" ] && {
 	mkdir -p "${common_boot_mnt}"
 	mount -o "defaults,${writeopt},errors=remount-ro" \
@@ -241,7 +235,7 @@ onie_mount_partitions()
 	onie_config_dir="${onie_config_ramdisk_dir}"
 	mkdir -p "${onie_config_dir}"
     }
-    
+
     [ -f "${fsck_flag_file}" ] && {
 	onie_config_dir="${onie_config_dir_orig}"
 	[ -d "${onie_config_dir}" -o "$writeopt" = "ro" ] || {
@@ -251,8 +245,49 @@ onie_mount_partitions()
         }
 	rmdir "${onie_config_ramdisk_dir}" > /dev/null 2>&1
     }
-    
+
     return 0
+}
+
+# Re-install ONIE GRUB in the MBR
+bios_boot_onie_install() {
+
+onie_dev=$(onie_get_boot_dev)
+boot_dev=$(onie_get_boot_disk)
+
+# Install ONIE GRUB in MBR and ONIE partition
+core_img="$onie_boot_mnt/grub/i386-pc/core.img"
+[ -f "$core_img" ] && chattr -i $core_img
+grub-install --boot-directory="$onie_boot_mnt" --recheck "$boot_dev" || {
+    echo "ERROR: grub-install failed on: $boot_dev"
+    exit 1
+}
+grub_install_log=$(mktemp)
+grub-install --force --boot-directory="$onie_boot_mnt" \
+    --recheck "$onie_dev" > /$grub_install_log 2>&1 || {
+    echo "ERROR: grub-install failed on: $onie_dev"
+    cat $grub_install_log && rm -f $grub_install_log
+    exit 1
+}
+rm -f $grub_install_log
+[ -f "$core_img" ] && chattr +i $core_img
+
+# If there is a diag partition add a chainload entry for it.
+diag_label=$(blkid | grep -- '-DIAG"' | sed -e 's/^.*LABEL="//' -e 's/".*$//')
+if [ -n "$diag_label" ] ; then
+    cat <<EOF >> $grub_root_dir/grub.cfg
+menuentry '$diag_label $onie_platform' {
+	search --no-floppy --label --set=root $diag_label
+	echo    'Loading $diag_label $onie_platform ...'
+	chainloader +1
+}
+EOF
+fi
+
+# Return to install mode on the next boot
+onie-boot-mode -q -o install
+
+return 0
 }
 
 # Local Variables:
